### ISSUE TITLE
3D (elevated) marker

### ISSUE THREAD

**Issue by mtpdog** [ramani-maps/ramani-maps#59]
Hello! How do you think is it theoretically possible to make such a 3D marker in Jetpack Compose for MapLibre part of Ramani Maps?

There's currently no support for 3D markers / z-axis (elevation) of markers in Maplibre. 
Please see the use case below which shows the markers projection point and it's altitude above ground (both parameters can be controlled separately):
https://www.youtube.com/watch?v=La3PkNGyZV4

<img width="659" alt="3dmarker" src="https://github.com/ramani-maps/ramani-maps/assets/150581563/1eda0d58-8ed5-4a20-b433-bd1a6d4f63af">

The [same question ](https://github.com/maplibre/maplibre-native/issues/1929) in the main Maplibre repository was kind of ignored.

**Comment by JonasVautherin** [comment]
> How do you think is it theoretically possible to make such a 3D marker in Jetpack Compose for MapLibre part of Ramani Maps?

I think that it has to be done in the MapLibre engine, because it is deeply integrated with the map. Once MapLibre supports it, then Ramani can expose it (should be easy in Ramani; it's just a matter of adding an elevation next to the LatLng).

> There's currently no support for 3D markers / z-axis (elevation) of markers in Maplibre.

I don't know about that, but I trust you here :blush:.

> The https://github.com/maplibre/maplibre-native/issues/1929in the main Maplibre repository was kind of ignored.

I don't think it was ignored, but maybe you missed that @louwers (the maintainer) marked it as "enhancement". Which means that he has seen it, and there is apparently no easier solution than contributing it to MapLibre.

Would you be willing to start looking into that? It would be interesting to continue the discussion in https://github.com/maplibre/maplibre-native/issues/1929 and try to understand how hard this would be in MapLibre. Maybe it's not too hard :crossed_fingers:.

I completely understand your use-case where you want to see the elevation of the drone waypoint :+1:.

**Comment by mtpdog** [comment]
OK. Thank you for your response!
It seems it is hard to do this until the full 3D mode is implemented in Maplibre.
