### ISSUE TITLE
Multiplatform support

### ISSUE THREAD

**Issue by westnordost** [ramani-maps/ramani-maps#77]
Currently, this library is based on **Jetpack Compose** and **MapLibre native Android**.

Could it be made to be based on/compatible with **Compose Multiplatform** and for the iOS side, use **MapLibre native iOS** under the hood? (MapLibre folks are contemplating whether to work on a proper C-Api, so that future versions might even use that directly.)

Would you say that the API of your library is generic enough that it would be eligible for a MapLibre-in-compose implementation that would cover _all the features_ of MapLibre or would it rather just serve as a base and/or inspiration?
(I remember that on the SotM Antwerp you mentioned that you made this library primarily to solve your specific use case which might mean that you e.g. added some sleek API that couldn't be used for a generic case.)

See also https://github.com/maplibre/maplibre-native/issues/2638

**Comment by JonasVautherin** [comment]
> Could it be made to be based on/compatible with Compose Multiplatform

Good question. What would it take for Ramani-Maps to be compatible with Compose Multiplatform instead of Jetpack Compose? I am not aware of the difference there :thinking:.

> and for the iOS side, use MapLibre native iOS under the hood?

Completely open to that, yes! If you manage to make a proof of concept, we could look into whether we can bring that upstream or not! My main requirement right now would be that I don't want it to be solved with a WebView and Javascript: it has to be "native".

> I remember that on the SotM Antwerp you mentioned that you made this library primarily to solve your specific use case which might mean that you e.g. added some sleek API that couldn't be used for a generic case.

Hmm I guess my point was that it is a pure open source project: we do it on a best-effort basis, we are open to contributions (without committing to merge everything), and the project is MPLv2-licensed, so people who are not happy with the way we maintain it can fork away :blush:.

So we are of course happy to welcome contributions into Ramani-Maps!

**Comment by westnordost** [comment]
> Good question. What would it take for Ramani-Maps to be compatible with Compose Multiplatform instead of Jetpack Compose? I am not aware of the difference there 🤔.

Sorry, don't know either. I've seen some compose libraries that work with either Compose Multiplatform or Jetpack Compose. Don't know how they do that. I guess, at least not use any feature of Jetpack Compose that is not in Compose Multiplatform (such as ´painterResource(<android drawable resource id>)´. But how the gradle setup needs to look, don't know.

> I don't want it to be solved with a WebView and Javascript: it has to be "native".

I don't think anyone is considering that, haha, hopefully.

**Comment by JonasVautherin** [comment]
I will close this if you don't mind. If anyone is willing to work on this or has insights on how it could be done, please feel free to reopen.
